//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.21.0.5
//     Timestamp      : 2025/1/31 22:16:10
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
USING System
USING System.Collections.Generic
USING System.ComponentModel
USING System.Data
USING System.Drawing
USING System.Text
USING System.Windows.Forms

USING XSharp.VFP.UI
// Templates/Designer/StartType.prg

PUBLIC PARTIAL CLASS Form1
 // INHERIT XSharp.VFP.UI.Form

		PUBLIC Text1 AS XSharp.VFP.UI.TextBox
    PUBLIC Label1 AS XSharp.VFP.UI.Label
    PUBLIC Command1 AS XSharp.VFP.UI.CommandButton
    PUBLIC cmdQuit AS XSharp.VFP.UI.CommandButton


		/// <summary>
        /// Required designer variable.
        /// </summary>
        PRIVATE components := NULL AS System.ComponentModel.IContainer
        

        
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

                PRIVATE METHOD InitializeComponent() AS VOID STRICT
        SELF:Text1 := XSharp.VFP.UI.TextBox{}
        SELF:Label1 := XSharp.VFP.UI.Label{}
        SELF:Command1 := XSharp.VFP.UI.CommandButton{}
        SELF:cmdQuit := XSharp.VFP.UI.CommandButton{}
        SELF:SuspendLayout()
        // 
        // Text1
        // 
        SELF:Text1:Alignment := 0
        SELF:Text1:Anchor := ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)  ;
                    | System.Windows.Forms.AnchorStyles.Right)))
        SELF:Text1:AutoComplete := 0
        SELF:Text1:AutoCompSource := ""
        SELF:Text1:AutoCompTable := ""
        SELF:Text1:BackColor := System.Drawing.Color.Transparent
        SELF:Text1:BorderColor := 0
        SELF:Text1:Century := 0
        SELF:Text1:DateFormat := 0
        SELF:Text1:DateMark := ""
        SELF:Text1:EnableHyperLinks := false
        SELF:Text1:FontName := "宋体"
        SELF:Text1:FontSize := 9
        SELF:Text1:Format := NULL
        SELF:Text1:Hours := 0
        SELF:Text1:InputMask := NULL
        SELF:Text1:IntegralHeight := 0
        SELF:Text1:Location := System.Drawing.Point{96, 72}
        SELF:Text1:Name := "Text1"
        SELF:Text1:NullDisplay := ""
        SELF:Text1:OLEDragPicture := ""
        SELF:Text1:OLEDropTextInsertion := 0
        SELF:Text1:Seconds := 0
        SELF:Text1:SelectedBackColor := 0
        SELF:Text1:SelectedForeColor := 0
        SELF:Text1:SelectOnEntry := false
        SELF:Text1:Size := System.Drawing.Size{168, 25}
        SELF:Text1:StrictDateEntry := 0
        SELF:Text1:TabIndex := 3
        SELF:Text1:ZOrderSet := 3
        // 
        // Label1
        // 
        SELF:Label1:Alignment := 4
        SELF:Label1:BackColor := System.Drawing.Color.Transparent
        SELF:Label1:Caption := "Name"
        SELF:Label1:FontName := "宋体"
        SELF:Label1:FontSize := 9
        SELF:Label1:Location := System.Drawing.Point{44, 75}
        SELF:Label1:Name := "Label1"
        SELF:Label1:OLEDragPicture := ""
        SELF:Label1:Rotation := 0
        SELF:Label1:Size := System.Drawing.Size{44, 16}
        SELF:Label1:Style := 0
        SELF:Label1:TabIndex := 2
        SELF:Label1:Text := "Name"
        SELF:Label1:WordWrap := false
        SELF:Label1:ZOrderSet := 2
        // 
        // Command1
        // 
        SELF:Command1:Anchor := ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)))
        SELF:Command1:BackColor := System.Drawing.Color.Transparent
        SELF:Command1:Caption := "OK"
        SELF:Command1:FontName := "宋体"
        SELF:Command1:FontSize := 9
        SELF:Command1:Location := System.Drawing.Point{276, 72}
        SELF:Command1:Name := "Command1"
        SELF:Command1:OLEDragPicture := ""
        SELF:Command1:Size := System.Drawing.Size{60, 25}
        SELF:Command1:Style := 0
        SELF:Command1:TabIndex := 1
        SELF:Command1:Text := "OK"
        SELF:Command1:UseVisualStyleBackColor := false
        SELF:Command1:vfpCLick := "Command1_Click"
        SELF:Command1:ZOrderSet := 1
        SELF:Command1:Click += System.EventHandler{ SELF, @Command1_Click() }
        // 
        // cmdQuit
        // 
        SELF:cmdQuit:Anchor := ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)))
        SELF:cmdQuit:BackColor := System.Drawing.Color.Transparent
        SELF:cmdQuit:Caption := "Quit"
        SELF:cmdQuit:FontName := "宋体"
        SELF:cmdQuit:FontSize := 9
        SELF:cmdQuit:Location := System.Drawing.Point{276, 168}
        SELF:cmdQuit:Name := "cmdQuit"
        SELF:cmdQuit:OLEDragPicture := ""
        SELF:cmdQuit:Size := System.Drawing.Size{60, 25}
        SELF:cmdQuit:Style := 0
        SELF:cmdQuit:TabIndex := 0
        SELF:cmdQuit:Text := "Quit"
        SELF:cmdQuit:UseVisualStyleBackColor := false
        SELF:cmdQuit:vfpCLick := "cmdQuit_Click"
        // 
        // Form1
        // 
        SELF:AutoCenter := true
        SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.None
        SELF:Caption := "Test"
        SELF:ClientSize := System.Drawing.Size{375, 223}
        SELF:Controls:Add(SELF:cmdQuit)
        SELF:Controls:Add(SELF:Command1)
        SELF:Controls:Add(SELF:Label1)
        SELF:Controls:Add(SELF:Text1)
        SELF:Name := "Form1"
        SELF:ShowWindowState := 2
        SELF:Text := "Test"
        SELF:ResumeLayout(false)
        SELF:PerformLayout()
    END METHOD


	END CLASS 
